apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-advanced-lab
resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
labels:
  - pairs:
      platform-lab.io/lab: argo-advanced
    includeSelectors: false
