apiVersion: v1
kind: Namespace
metadata:
  name: argo-advanced-lab
  labels:
    app.kubernetes.io/name: argo-advanced-lab
    app.kubernetes.io/part-of: platform-lab
    platform-lab.io/lab: argo-advanced
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
