apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-app-of-apps
    app.kubernetes.io/part-of: platform-lab
    platform-lab.io/lab: argo-advanced
spec:
  project: platform-advanced-lab
  source:
    repoURL: https://github.com/kirandevraaj/kubernetes-platform-engineering-gitops.git
    targetRevision: main
    path: kubernetes/argo-app-of-apps/children
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
