apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Do not set a global namespace: StorageClass is cluster-scoped.
resources:
  - namespace.yaml
  - storageclass.yaml
  - service.yaml
  - statefulset.yaml
