apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-lab
resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
images:
  - name: kirandevraaj/platform-lab
    digest: sha256:945424e996f474c4cac45dd18c8c38319394a790ae00a2cd68c5ce9059461b96
# Version label = logical release; digest = immutable artifact (Jenkins updates both).
labels:
  - pairs:
      app.kubernetes.io/version: "0.1.5"
    includeSelectors: false
    includeTemplates: true
patches:
  - path: configmap-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: platform-lab-config
  - path: ingress-alb-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: platform-lab
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: platform-lab
    patch: |-
      - op: replace
        path: /spec/ingress
        value:
          - from:
              - ipBlock:
                  cidr: 10.50.0.0/16
            ports:
              - protocol: TCP
                port: 8000
  - path: deployment-reliability-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: platform-lab
