apiVersion: v1
kind: Service
metadata:
  name: automation-demo
  namespace: automation-lab
  labels:
    app: automation-demo
    lab: automation-lab
spec:
  selector:
    app: automation-demo
  ports:
    - port: 80
      targetPort: 80
