apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-lab-config
  labels:
    app.kubernetes.io/name: platform-lab
    app.kubernetes.io/instance: platform-lab
    app.kubernetes.io/component: api
    app.kubernetes.io/version: "0.1.0"
data:
  APP_ENVIRONMENT: local
