apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-lab
  labels:
    app.kubernetes.io/name: platform-lab
    app.kubernetes.io/instance: platform-lab
    app.kubernetes.io/component: api
automountServiceAccountToken: false
