apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-demo-config
  namespace: argo-advanced-lab
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: argo-order-demo
    app.kubernetes.io/part-of: argo-advanced-lab
data:
  demo.message: "Wave-ordered ConfigMap (wave -1)"
  demo.phase: "waves"
---
apiVersion: v1
kind: Service
metadata:
  name: argo-order-demo
  namespace: argo-advanced-lab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: argo-order-demo
    app.kubernetes.io/part-of: argo-advanced-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argo-order-demo
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-order-demo
  namespace: argo-advanced-lab
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: argo-order-demo
    app.kubernetes.io/part-of: argo-advanced-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-order-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-order-demo
        app.kubernetes.io/part-of: argo-advanced-lab
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
