apiVersion: v1
kind: Namespace
metadata:
  name: storage-lab
  labels:
    app.kubernetes.io/name: storage-lab
    app.kubernetes.io/part-of: platform-lab
    app.kubernetes.io/component: storage-lab
