apiVersion: v1
kind: Service
metadata:
  name: storage-demo
  namespace: storage-lab
  labels:
    app.kubernetes.io/name: storage-demo
    app.kubernetes.io/instance: storage-demo
    app.kubernetes.io/part-of: storage-lab
    app.kubernetes.io/component: stateful
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: storage-demo
    app.kubernetes.io/instance: storage-demo
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
