apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-storage-aws
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-storage-aws
    app.kubernetes.io/part-of: platform-lab
    platform-lab.io/target: aws
spec:
  description: AWS EBS CSI StatefulSet storage lab (isolated from platform-lab-aws)
  sourceRepos:
    - https://github.com/kirandevraaj/kubernetes-platform-engineering-gitops.git
  destinations:
    - namespace: storage-lab
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: StatefulSet
  orphanedResources:
    warn: true
