apiVersion: v1
kind: Namespace
metadata:
  name: argo-child-service
  labels:
    app.kubernetes.io/name: argo-child-service
    platform-lab.io/lab: argo-advanced
---
apiVersion: v1
kind: Service
metadata:
  name: child-service
  namespace: argo-child-service
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: child-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: child-workload
  ports:
    - name: http
      port: 8080
      targetPort: http
