apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress-nginx-controller-service.yaml
  - servicemonitor.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: kirandevraaj/platform-lab
    newTag: "0.1.3"
patches:
  - path: networkpolicy-prometheus-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: platform-lab
  - path: deployment-reliability-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: platform-lab
