apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-reader
  namespace: security-lab
  labels:
    app.kubernetes.io/name: security-reader
    app.kubernetes.io/part-of: security-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-writer
  namespace: security-lab
  labels:
    app.kubernetes.io/name: security-writer
    app.kubernetes.io/part-of: security-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-node-reader
  namespace: security-lab
  labels:
    app.kubernetes.io/name: security-node-reader
    app.kubernetes.io/part-of: security-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-global-reader
  namespace: security-lab
  labels:
    app.kubernetes.io/name: security-global-reader
    app.kubernetes.io/part-of: security-lab
